name: wechat_assets_picker
description: An assets' picker written in pure Dart which looks like the one in WeChat, support multi asset pick from the device.
version: 4.1.1+2
homepage: https://github.com/fluttercandies/flutter_wechat_assets_picker

environment:
  sdk: ">=2.8.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  extended_image: 3.0.0
  photo_manager: 1.0.3
  # provider: ^4.3.2+2
  provider: 5.0.0
  toast: ^0.1.5
  # video_player: ">=0.11.0 <2.0.0"
  video_player: "2.0.2"

